import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/Header';
import '@/styles/globals.css'
import { Side } from '@/components/side/Side';
import { SessionProvider } from 'next-auth/react';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { auth } from "@/services/auth";

const inter = Inter({ subsets: ['latin'] })

export const dynamicParams = true // true | false,


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider session={session}>
            {/* <Header /> */}
        
            {children}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

